services:
  - type: web
    name: 100ktracker-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_PATH
        value: /app/db/users.sqlite
      - key: APP_URL
        value: https://100ktracker.netlify.app
    healthCheckPath: /health
    healthCheckDelay: 30
    healthCheckPeriod: 30
    healthCheckTimeout: 5
    healthCheckFailureThreshold: 3
    autoDeploy: true
    disk:
      name: 100ktracker-data
      mountPath: /app/db
      sizeGB: 10
