services:
  - type: web
    name: 100ktracker-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_PATH
        value: ./db/database.sqlite
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: 100ktracker-data
      mountPath: /app/db
      sizeGB: 1
